/**
 * Claude compiler — compiles CLAUDE.md using @import-style references for
 * Claude Code.  Each instruction and chatmode is referenced by its path
 * relative to the project root so Claude Code can load the files on demand.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { Chatmode, Instruction } from '../models/primitives.js';
import { emptyDiscoveredPrimitives } from '../models/primitives.js';
import {
  discoverProjectPrimitives,
  discoverInstalledPrimitives,
} from '../primitives/discovery.js';
import * as log from '../utils/console.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ClaudeCompileOptions {
  projectRoot: string;
  dryRun?: boolean;
  /** Ignore apm_modules/ when true */
  localOnly?: boolean;
  /** Reserved for future use; @import refs do not inline content */
  resolveLinks?: boolean;
}

export interface ClaudeCompileResult {
  filesWritten: string[];
  totalInstructions: number;
}

// ---------------------------------------------------------------------------
// ClaudeCompiler
// ---------------------------------------------------------------------------

export class ClaudeCompiler {
  async compile(opts: ClaudeCompileOptions): Promise<ClaudeCompileResult> {
    const result: ClaudeCompileResult = {
      filesWritten: [],
      totalInstructions: 0,
    };

    // Gather primitives
    const projectPrims = discoverProjectPrimitives(opts.projectRoot);
    const installedPrims = opts.localOnly
      ? emptyDiscoveredPrimitives()
      : discoverInstalledPrimitives(opts.projectRoot);

    const allInstructions = [...projectPrims.instructions, ...installedPrims.instructions];
    const allChatmodes = [...projectPrims.chatmodes, ...installedPrims.chatmodes];

    result.totalInstructions = allInstructions.length;

    log.header(
      `Compiling ${allInstructions.length} instruction(s) + ${allChatmodes.length} chatmode(s) → CLAUDE.md`,
    );

    const outputPath = path.join(opts.projectRoot, 'CLAUDE.md');
    const content = this.buildClaudeMdContent(allInstructions, allChatmodes);

    if (opts.dryRun) {
      log.dim(`[dry-run] Would write: ${outputPath}`);
      return result;
    }

    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, content, 'utf-8');
    log.success(`Written: ${outputPath}`);
    result.filesWritten.push(outputPath);

    return result;
  }

  // ── Content builder ──────────────────────────────────────────────────────

  /**
   * Build CLAUDE.md content using @import references.
   *
   * Claude Code resolves `@path/to/file.md` relative to the directory that
   * contains CLAUDE.md (the project root in our case), so `relativePath` on
   * each primitive must already be project-root-relative.
   */
  private buildClaudeMdContent(instructions: Instruction[], chatmodes: Chatmode[]): string {
    let content = '# Agent Instructions\n\n';
    content += '<!-- Generated by napm. Do not edit manually. -->\n\n';

    if (instructions.length > 0) {
      for (const instr of instructions) {
        content += `@${instr.relativePath}\n`;
      }
    }

    if (chatmodes.length > 0) {
      content += '\n## Agents\n\n';
      for (const cm of chatmodes) {
        content += `@${cm.relativePath}\n`;
      }
    }

    return content;
  }
}
